[package]
name = "rdf-compare"
version = "0.1.0"
edition = "2024"
description = "Fast CLI to compute the diff of two RDF files as a quad dataset with two named graphs"
authors = ["Mathias Vanden Auweele <mathias@matdata.eu>"]
license = "Apache-2.0"
homepage = "https://github.com/Matdata-eu/rdf-compare"
repository = "https://github.com/Matdata-eu/rdf-compare"
categories = ["command-line-utilities", "science::geo"]
readme = "README.md"

[dependencies]
anyhow = "1"
axum = { version = "0.7", default-features = false, features = ["http1", "tokio", "json", "query"] }
clap = { version = "4", features = ["derive"] }
flate2 = "1"
oxrdf = { version = "0.3", features = ["rdfc-10"] }
oxrdfxml = "0.2"
oxttl = "0.2"
percent-encoding = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros", "net", "io-util", "signal", "sync"] }
tokio-stream = { version = "0.1", features = ["sync"] }
webbrowser = "1"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
